export enum ConfigKey {
    BACKEND_PORT = "BACKEND_PORT",
    DATABASE_HOST = "DATABASE_HOST",
    DATABASE_NAME = "DATABASE_NAME",
    DATABASE_USER = "DATABASE_USER",
    DATABASE_PASSWORD = "DATABASE_PASSWORD",
    DATABASE_PORT = "DATABASE_PORT",
    NODE_ENV = "NODE_ENV",
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRATION = 'JWT_EXPIRATION',
}

export enum NodeEnvironment {
    DEVELOPMENT = "development",
    PRODUCTION = "production",
    LOCAL = "local"
}